"""VulnForge Report Router - Security report generation endpoint."""

import json
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field

router = APIRouter(tags=["report"])


class ReportRequest(BaseModel):
    """Request body for report generation."""
    contract_name: str = Field(..., description="Contract name")
    solidity_version: str = Field(default="unknown", description="Solidity version")
    overall_risk: str = Field(default="UNKNOWN", description="Overall risk rating")
    vulnerabilities: list[dict] = Field(default_factory=list, description="Vulnerability findings")
    exploit_results: list[dict] = Field(default_factory=list, description="Exploit execution results")
    patch_result: dict | None = Field(default=None, description="Patch generation result")


def _generate_markdown_report(data: ReportRequest) -> str:
    """Generate a markdown security report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    risk_emoji = {
        "CRITICAL": "🔴",
        "HIGH": "🟠",
        "MEDIUM": "🟡",
        "LOW": "🔵",
        "SAFE": "🟢",
    }

    lines = [
        f"# VulnForge Security Report",
        f"",
        f"**Contract:** `{data.contract_name}`",
        f"**Solidity Version:** `{data.solidity_version}`",
        f"**Overall Risk:** {risk_emoji.get(data.overall_risk, '⚪')} **{data.overall_risk}**",
        f"**Scan Date:** {now}",
        f"**Generated by:** VulnForge AI Security Platform",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        f"This report presents the automated security analysis of `{data.contract_name}`. ",
        f"A total of **{len(data.vulnerabilities)}** vulnerability finding(s) were identified.",
        f"",
    ]

    # Vulnerability summary table
    if data.vulnerabilities:
        critical = sum(1 for v in data.vulnerabilities if v.get("severity") == "CRITICAL")
        high = sum(1 for v in data.vulnerabilities if v.get("severity") == "HIGH")
        medium = sum(1 for v in data.vulnerabilities if v.get("severity") == "MEDIUM")
        low = sum(1 for v in data.vulnerabilities if v.get("severity") == "LOW")

        lines.extend([
            "## Vulnerability Summary",
            "",
            "| Severity | Count |",
            "|----------|-------|",
            f"| 🔴 Critical | {critical} |",
            f"| 🟠 High | {high} |",
            f"| 🟡 Medium | {medium} |",
            f"| 🔵 Low | {low} |",
            "",
        ])

        # Detailed findings
        lines.extend([
            "## Detailed Findings",
            "",
        ])

        for i, vuln in enumerate(data.vulnerabilities, 1):
            sev = vuln.get("severity", "UNKNOWN")
            emoji = risk_emoji.get(sev, "⚪")
            lines.extend([
                f"### {i}. {vuln.get('title', 'Unknown')} {emoji}",
                f"",
                f"- **ID:** `{vuln.get('id', 'N/A')}`",
                f"- **Severity:** {emoji} {sev}",
                f"- **Type:** `{vuln.get('type', 'N/A')}`",
                f"- **CWE:** `{vuln.get('cwe', 'N/A')}`",
                f"- **Lines:** L{vuln.get('line_start', 0)}–L{vuln.get('line_end', 0)}",
                f"- **Function:** `{vuln.get('affected_function', 'N/A')}`",
                f"- **Exploit Possible:** {'Yes' if vuln.get('exploit_possible') else 'No'}",
                f"",
                f"**Description:** {vuln.get('description', 'N/A')}",
                f"",
                f"**Attack Vector:** {vuln.get('attack_vector', 'N/A')}",
                f"",
                f"**Impact:** {vuln.get('impact', 'N/A')}",
                f"",
                f"**Recommendation:** {vuln.get('recommendation', 'N/A')}",
                f"",
                f"---",
                f"",
            ])

    # Exploit results
    if data.exploit_results:
        lines.extend([
            "## Proof-of-Exploit Results",
            "",
        ])
        for i, exploit in enumerate(data.exploit_results, 1):
            success = exploit.get("success", False)
            status_icon = "✅" if success else "❌"
            lines.extend([
                f"### Exploit {i}: {status_icon} {'Success' if success else 'Failed'}",
                f"",
                f"- **Job ID:** `{exploit.get('job_id', 'N/A')}`",
                f"- **Status:** {exploit.get('status', 'N/A')}",
            ])
            if exploit.get("drained"):
                lines.append(f"- **Drained:** {exploit['drained']} ETH")
            if exploit.get("error"):
                lines.append(f"- **Error:** {exploit['error']}")
            lines.extend(["", "---", ""])

    # Patch section
    if data.patch_result:
        lines.extend([
            "## Remediation Patch",
            "",
            f"**Compilation Notes:** {data.patch_result.get('compilation_notes', 'N/A')}",
            "",
            "### Fixes Applied:",
            "",
        ])
        for fix in data.patch_result.get("fixes_applied", []):
            lines.extend([
                f"- **{fix.get('type', 'UNKNOWN')}:** {fix.get('fix_summary', 'N/A')}",
                f"  - Vulnerability: `{fix.get('vulnerability_id', 'N/A')}`",
                f"  - Breaking Changes: {'Yes' if fix.get('breaking_changes') else 'No'}",
            ])
        lines.append("")

    lines.extend([
        "---",
        "",
        f"*Report generated on {now} by [VulnForge](https://github.com/vulnforge) — AI-Powered Smart Contract Security*",
    ])

    return "\n".join(lines)


@router.post("/report", response_class=PlainTextResponse)
async def generate_report(request: ReportRequest) -> str:
    """Generate a markdown security report.

    Creates a comprehensive security report from analysis results,
    exploit outcomes, and patch information.

    Args:
        request: Report data including vulnerabilities, exploits, and patches.

    Returns:
        Markdown-formatted security report.
    """
    return _generate_markdown_report(request)
